[package]
name = "fib"
version = "0.1.0"
authors = ["nakamuray"]

[lib]
name = "hello"
crate-type = ["cdylib"]

[dependencies]
rayon = "0.7"

[dependencies.cpython]
version = "0.1"
features = ["extension-module"]
